#  Copyright 2017-2026 Karl T Debiec. All rights reserved. This software may be modified
#  and distributed under the terms of the BSD license. See the LICENSE file for details.
"""Caches OCR results."""

from __future__ import annotations

import hashlib
import json
from abc import ABC, abstractmethod
from collections.abc import Mapping
from logging import getLogger
from pathlib import Path

from PIL import Image

from scinoephile.common.file import open_atomic_text_file
from scinoephile.common.validation import val_output_dir_path
from scinoephile.core.cache.artifact import remove_cache_artifact
from scinoephile.core.cache.identity import CacheIdentity
from scinoephile.core.paths import get_runtime_cache_root_path
from scinoephile.image.cache_namespace import ImageCacheNamespace

__all__ = ["OcrCacheBase"]

logger = getLogger(__name__)


class OcrCacheBase[TResult](ABC):
    """Caches OCR results by image and recognizer configuration."""

    def __init__(
        self,
        cache_root_path: Path | None,
        cache_namespace: ImageCacheNamespace,
        backend_label: str,
        cache_version: int,
        overwrite: bool = False,
    ):
        """Initialize.

        Arguments:
            cache_root_path: root directory beneath which to cache, or None for default
            cache_namespace: registered OCR result namespace
            backend_label: human-readable backend name used in log messages
            cache_version: current backend cache version
            overwrite: whether to replace matching cache files
        """
        self.backend_label = backend_label
        """Human-readable backend name used in log messages."""
        self._version = cache_version
        """Current backend cache version."""

        if cache_root_path is None:
            cache_root_path = get_runtime_cache_root_path()
        self.cache_root_path = val_output_dir_path(cache_root_path)
        """Root directory beneath which OCR results are cached."""
        self.cache_dir_path = cache_namespace.get_dir_path(self.cache_root_path)
        """Directory in which cached OCR results are stored."""

        self.overwrite = overwrite
        """Whether to replace matching cache files."""

        self._refreshed_paths: set[Path] = set()
        """Cache paths refreshed by this cache instance."""

    def get_path(self, image: Image.Image, cache_identity: CacheIdentity) -> Path:
        """Get the cache path for an image and recognizer configuration.

        Arguments:
            image: image used to derive the cache key
            cache_identity: backend configuration identifying the result
        Returns:
            cache path
        """
        cache_hash = hashlib.sha256(image.tobytes())
        cache_hash.update(b"\0")
        cache_hash.update(
            json.dumps(
                {**cache_identity, "image_mode": image.mode, "image_size": image.size},
                ensure_ascii=False,
                sort_keys=True,
            ).encode("utf-8")
        )
        return self.cache_dir_path / f"{cache_hash.hexdigest()}.json"

    def load(self, image: Image.Image, cache_identity: CacheIdentity) -> TResult | None:
        """Load a cached OCR result.

        Invalid cache files are discarded and treated as cache misses.

        Arguments:
            image: image used to derive the cache key
            cache_identity: backend configuration identifying the result
        Returns:
            cached result, if present and valid

        Raises:
            ValueError: if a value is invalid
        """
        cache_path = self.get_path(image, cache_identity)
        # An overwrite request converts a matching entry into a cache miss
        if self.overwrite and cache_path not in self._refreshed_paths:
            self._refreshed_paths.add(cache_path)
            if remove_cache_artifact(cache_path):
                logger.info(f"Removed {self.backend_label} cache: {cache_path}")
        if not cache_path.is_file() or cache_path.is_symlink():
            if remove_cache_artifact(cache_path):
                logger.warning(
                    f"Discarded invalid {self.backend_label} cache: {cache_path}"
                )
            return None

        # Invalid or unreadable entries are regenerated by the caller
        try:
            with cache_path.open("r", encoding="utf-8") as file:
                payload: object = json.load(file)
            if not isinstance(payload, Mapping):
                raise ValueError(f"{self.backend_label} cache must contain an object")
            if payload.get("cache_version") != self._version:
                raise ValueError(f"Unsupported {self.backend_label} cache version")
            result = self._deserialize(payload.get("result"))
        except (
            IndexError,
            KeyError,
            OSError,
            TypeError,
            UnicodeError,
            ValueError,
        ) as exc:
            remove_cache_artifact(cache_path)
            logger.warning(
                f"Discarded invalid {self.backend_label} cache {cache_path}: {exc}"
            )
            return None

        cache_path.touch()
        logger.info(f"Loaded {self.backend_label} result from cache: {cache_path}")
        return result

    def remove(self, image: Image.Image, cache_identity: CacheIdentity) -> Path | None:
        """Remove a cached OCR result.

        Arguments:
            image: image used to derive the cache key
            cache_identity: backend configuration identifying the result
        Returns:
            removed cache path, if present
        """
        cache_path = self.get_path(image, cache_identity)
        if not remove_cache_artifact(cache_path):
            return None
        logger.info(f"Removed {self.backend_label} cache: {cache_path}")
        return cache_path

    def save(
        self, image: Image.Image, cache_identity: CacheIdentity, result: TResult
    ) -> Path:
        """Save an OCR result to the cache.

        Arguments:
            image: image used to derive the cache key
            cache_identity: backend configuration identifying the result
            result: normalized OCR result to cache
        Returns:
            saved cache path
        """
        cache_path = self.get_path(image, cache_identity)
        with open_atomic_text_file(cache_path) as file:
            json.dump(
                {"cache_version": self._version, "result": self._serialize(result)},
                file,
                ensure_ascii=False,
            )
        self._refreshed_paths.add(cache_path)
        logger.info(f"Saved {self.backend_label} result to cache: {cache_path}")
        return cache_path

    @abstractmethod
    def _deserialize(self, payload: object) -> TResult:
        """Deserialize and validate a cached result.

        Arguments:
            payload: decoded JSON payload
        Returns:
            normalized OCR result
        """
        raise NotImplementedError()

    @abstractmethod
    def _serialize(self, result: TResult) -> object:
        """Serialize a normalized OCR result.

        Arguments:
            result: normalized OCR result
        Returns:
            JSON-serializable payload
        """
        raise NotImplementedError()
