#  Copyright 2017-2026 Karl T Debiec. All rights reserved. This software may be modified
#  and distributed under the terms of the BSD license. See the LICENSE file for details.
"""Caches OCR results."""

from __future__ import annotations

import hashlib
import json
from abc import ABC, abstractmethod
from collections.abc import Mapping
from logging import getLogger
from pathlib import Path

from PIL import Image

from scinoephile.common.file import open_atomic_text_file
from scinoephile.common.validation import val_output_dir_path

__all__ = ["OcrCache"]

logger = getLogger(__name__)


class OcrCache[TResult](ABC):
    """Caches OCR results by image and recognizer configuration."""

    def __init__(
        self,
        cache_root_path: Path | None,
        cache_dir_name: str,
        backend_label: str,
        overwrite: bool = False,
    ):
        """Initialize.

        Arguments:
            cache_root_path: root directory beneath which to cache, or None to disable
            cache_dir_name: cache subdirectory name
            backend_label: human-readable backend name used in log messages
            overwrite: whether to replace matching cache files
        """
        self.backend_label = backend_label
        """Human-readable backend name used in log messages."""

        self.cache_dir_path = None
        """Directory in which cached OCR results are stored."""
        if cache_root_path is not None:
            self.cache_dir_path = val_output_dir_path(cache_root_path / cache_dir_name)

        self.overwrite = overwrite
        """Whether to replace matching cache files."""

    @property
    def cache_root_path(self) -> Path | None:
        """Root directory beneath which OCR results are cached, or None if disabled."""
        if self.cache_dir_path is None:
            return None
        return self.cache_dir_path.parent

    def get_path(
        self,
        image: Image.Image,
        backend_metadata: Mapping[str, object],
    ) -> Path | None:
        """Get the cache path for an image and recognizer configuration.

        Arguments:
            image: image used to derive the cache key
            backend_metadata: backend configuration identifying the result
        Returns:
            cache path, or None when caching is disabled
        """
        if self.cache_dir_path is None:
            return None

        cache_hash = hashlib.sha256(image.tobytes())
        cache_hash.update(b"\0")
        cache_hash.update(
            json.dumps(
                {
                    "image_mode": image.mode,
                    "image_size": image.size,
                    **backend_metadata,
                },
                ensure_ascii=False,
                sort_keys=True,
            ).encode("utf-8")
        )
        return self.cache_dir_path / f"{cache_hash.hexdigest()}.json"

    def load(
        self,
        image: Image.Image,
        backend_metadata: Mapping[str, object],
    ) -> TResult | None:
        """Load a cached OCR result.

        Invalid cache files are discarded and treated as cache misses.

        Arguments:
            image: image used to derive the cache key
            backend_metadata: backend configuration identifying the result
        Returns:
            cached result, if present and valid
        """
        cache_path = self.get_path(image, backend_metadata)
        if cache_path is None:
            return None

        # An overwrite request converts a matching entry into a cache miss
        if self.overwrite and cache_path.exists():
            cache_path.unlink()
            logger.info(f"Removed {self.backend_label} cache: {cache_path}")
        if not cache_path.exists():
            return None

        # Invalid or unreadable entries are regenerated by the caller
        try:
            with cache_path.open("r", encoding="utf-8") as file:
                payload: object = json.load(file)
            result = self._deserialize(payload)
        except (
            IndexError,
            KeyError,
            OSError,
            TypeError,
            UnicodeError,
            ValueError,
        ) as exc:
            cache_path.unlink(missing_ok=True)
            logger.warning(
                f"Discarded invalid {self.backend_label} cache {cache_path}: {exc}"
            )
            return None

        cache_path.touch()
        logger.info(f"Loaded {self.backend_label} result from cache: {cache_path}")
        return result

    def save(
        self,
        image: Image.Image,
        backend_metadata: Mapping[str, object],
        result: TResult,
    ) -> Path | None:
        """Save an OCR result to the cache.

        Arguments:
            image: image used to derive the cache key
            backend_metadata: backend configuration identifying the result
            result: normalized OCR result to cache
        Returns:
            saved cache path, or None when caching is disabled
        """
        cache_path = self.get_path(image, backend_metadata)
        if cache_path is None:
            return None

        with open_atomic_text_file(cache_path) as file:
            json.dump(
                self._serialize(result),
                file,
                ensure_ascii=False,
            )
        logger.info(f"Saved {self.backend_label} result to cache: {cache_path}")
        return cache_path

    @abstractmethod
    def _deserialize(self, payload: object) -> TResult:
        """Deserialize and validate a cached result.

        Arguments:
            payload: decoded JSON payload
        Returns:
            normalized OCR result
        """
        raise NotImplementedError()

    @abstractmethod
    def _serialize(self, result: TResult) -> object:
        """Serialize a normalized OCR result.

        Arguments:
            result: normalized OCR result
        Returns:
            JSON-serializable payload
        """
        raise NotImplementedError()
