#  Copyright 2017-2026 Karl T Debiec. All rights reserved. This software may be modified
#  and distributed under the terms of the BSD license. See the LICENSE file for details.
"""Tests of clean_series."""

from __future__ import annotations

from pytest import FixtureRequest, param

from scinoephile.core import Language
from scinoephile.workflows.clean import clean_series
from test.helpers import assert_series_equal, parametrize


@parametrize(
    ("series_fixture", "expected_fixture", "language"),
    [
        param(
            "acopopb_eng_ocr_fuse",
            "acopopb_eng_ocr_fuse_clean",
            Language.eng,
            id="acopopb-eng-fuse",
        ),
        param(
            "acopopb_eng_ocr_lens",
            "acopopb_eng_ocr_lens_clean",
            Language.eng,
            id="acopopb-eng-lens",
        ),
        param(
            "acopopb_eng_ocr_tesseract",
            "acopopb_eng_ocr_tesseract_clean",
            Language.eng,
            id="acopopb-eng-tesseract",
        ),
        param(
            "acoptc_eng_ocr_fuse",
            "acoptc_eng_ocr_fuse_clean",
            Language.eng,
            id="acoptc-eng-fuse",
        ),
        param(
            "acoptc_eng_ocr_lens",
            "acoptc_eng_ocr_lens_clean",
            Language.eng,
            id="acoptc-eng-lens",
        ),
        param(
            "acoptc_eng_ocr_tesseract",
            "acoptc_eng_ocr_tesseract_clean",
            Language.eng,
            id="acoptc-eng-tesseract",
        ),
        param(
            "kob_eng_ocr_fuse",
            "kob_eng_ocr_fuse_clean",
            Language.eng,
            id="kob-eng-fuse",
        ),
        param(
            "kob_eng_ocr_lens",
            "kob_eng_ocr_lens_clean",
            Language.eng,
            id="kob-eng-lens",
        ),
        param(
            "kob_eng_ocr_tesseract",
            "kob_eng_ocr_tesseract_clean",
            Language.eng,
            id="kob-eng-tesseract",
        ),
        param(
            "kob_eng",
            "kob_eng_clean",
            Language.eng,
            id="kob-eng-srt",
        ),
        param(
            "mlamd_eng_fuse",
            "mlamd_eng_fuse_clean",
            Language.eng,
            id="mlamd-eng-fuse",
        ),
        param(
            "mlamd_eng_ocr_lens",
            "mlamd_eng_ocr_lens_clean",
            Language.eng,
            id="mlamd-eng-lens",
        ),
        param(
            "mlamd_eng_ocr_tesseract",
            "mlamd_eng_ocr_tesseract_clean",
            Language.eng,
            id="mlamd-eng-tesseract",
        ),
        param(
            "mnt_eng_fuse",
            "mnt_eng_fuse_clean",
            Language.eng,
            id="mnt-eng-fuse",
        ),
        param(
            "mnt_eng_ocr_lens",
            "mnt_eng_ocr_lens_clean",
            Language.eng,
            id="mnt-eng-lens",
        ),
        param(
            "mnt_eng_ocr_tesseract",
            "mnt_eng_ocr_tesseract_clean",
            Language.eng,
            id="mnt-eng-tesseract",
        ),
        param(
            "t_eng_fuse",
            "t_eng_fuse_clean",
            Language.eng,
            id="t-eng-fuse",
        ),
        param(
            "t_eng_ocr_lens",
            "t_eng_ocr_lens_clean",
            Language.eng,
            id="t-eng-lens",
        ),
        param(
            "t_eng_ocr_tesseract",
            "t_eng_ocr_tesseract_clean",
            Language.eng,
            id="t-eng-tesseract",
        ),
        param(
            "tmm_eng_ocr_fuse",
            "tmm_eng_ocr_fuse_clean",
            Language.eng,
            id="tmm-eng-fuse",
        ),
        param(
            "tmm_eng_ocr_lens",
            "tmm_eng_ocr_lens_clean",
            Language.eng,
            id="tmm-eng-lens",
        ),
        param(
            "tmm_eng_ocr_tesseract",
            "tmm_eng_ocr_tesseract_clean",
            Language.eng,
            id="tmm-eng-tesseract",
        ),
        param(
            "acopopb_yue_hans_ocr_fuse",
            "acopopb_yue_hans_ocr_fuse_clean",
            Language.yue_hans,
            id="acopopb-yue-hans-fuse",
        ),
        param(
            "acopopb_yue_hans_ocr_lens",
            "acopopb_yue_hans_ocr_lens_clean",
            Language.yue_hans,
            id="acopopb-yue-hans-lens",
        ),
        param(
            "acopopb_yue_hans_ocr_paddle",
            "acopopb_yue_hans_ocr_paddle_clean",
            Language.yue_hans,
            id="acopopb-yue-hans-paddle",
        ),
        param(
            "acopopb_yue_hant_ocr_fuse",
            "acopopb_yue_hant_ocr_fuse_clean",
            Language.yue_hant,
            id="acopopb-yue-hant-fuse",
        ),
        param(
            "acopopb_yue_hant_ocr_lens",
            "acopopb_yue_hant_ocr_lens_clean",
            Language.yue_hant,
            id="acopopb-yue-hant-lens",
        ),
        param(
            "acopopb_yue_hant_ocr_paddle",
            "acopopb_yue_hant_ocr_paddle_clean",
            Language.yue_hant,
            id="acopopb-yue-hant-paddle",
        ),
        param(
            "acopopb_zho_hans_ocr_fuse",
            "acopopb_zho_hans_ocr_fuse_clean",
            Language.zho_hans,
            id="acopopb-zho-hans-fuse",
        ),
        param(
            "acopopb_zho_hans_ocr_lens",
            "acopopb_zho_hans_ocr_lens_clean",
            Language.zho_hans,
            id="acopopb-zho-hans-lens",
        ),
        param(
            "acopopb_zho_hans_ocr_paddle",
            "acopopb_zho_hans_ocr_paddle_clean",
            Language.zho_hans,
            id="acopopb-zho-hans-paddle",
        ),
        param(
            "acopopb_zho_hant_ocr_fuse",
            "acopopb_zho_hant_ocr_fuse_clean",
            Language.zho_hant,
            id="acopopb-zho-hant-fuse",
        ),
        param(
            "acopopb_zho_hant_ocr_lens",
            "acopopb_zho_hant_ocr_lens_clean",
            Language.zho_hant,
            id="acopopb-zho-hant-lens",
        ),
        param(
            "acopopb_zho_hant_ocr_paddle",
            "acopopb_zho_hant_ocr_paddle_clean",
            Language.zho_hant,
            id="acopopb-zho-hant-paddle",
        ),
        param(
            "acoptc_yue_hans_ocr_fuse",
            "acoptc_yue_hans_ocr_fuse_clean",
            Language.yue_hans,
            id="acoptc-yue-hans-fuse",
        ),
        param(
            "acoptc_yue_hans_ocr_lens",
            "acoptc_yue_hans_ocr_lens_clean",
            Language.yue_hans,
            id="acoptc-yue-hans-lens",
        ),
        param(
            "acoptc_yue_hans_ocr_paddle",
            "acoptc_yue_hans_ocr_paddle_clean",
            Language.yue_hans,
            id="acoptc-yue-hans-paddle",
        ),
        param(
            "acoptc_yue_hant_ocr_fuse",
            "acoptc_yue_hant_ocr_fuse_clean",
            Language.yue_hant,
            id="acoptc-yue-hant-fuse",
        ),
        param(
            "acoptc_yue_hant_ocr_lens",
            "acoptc_yue_hant_ocr_lens_clean",
            Language.yue_hant,
            id="acoptc-yue-hant-lens",
        ),
        param(
            "acoptc_yue_hant_ocr_paddle",
            "acoptc_yue_hant_ocr_paddle_clean",
            Language.yue_hant,
            id="acoptc-yue-hant-paddle",
        ),
        param(
            "acoptc_zho_hans_ocr_fuse",
            "acoptc_zho_hans_ocr_fuse_clean",
            Language.zho_hans,
            id="acoptc-zho-hans-fuse",
        ),
        param(
            "acoptc_zho_hans_ocr_lens",
            "acoptc_zho_hans_ocr_lens_clean",
            Language.zho_hans,
            id="acoptc-zho-hans-lens",
        ),
        param(
            "acoptc_zho_hans_ocr_paddle",
            "acoptc_zho_hans_ocr_paddle_clean",
            Language.zho_hans,
            id="acoptc-zho-hans-paddle",
        ),
        param(
            "acoptc_zho_hant_ocr_fuse",
            "acoptc_zho_hant_ocr_fuse_clean",
            Language.zho_hant,
            id="acoptc-zho-hant-fuse",
        ),
        param(
            "acoptc_zho_hant_ocr_lens",
            "acoptc_zho_hant_ocr_lens_clean",
            Language.zho_hant,
            id="acoptc-zho-hant-lens",
        ),
        param(
            "acoptc_zho_hant_ocr_paddle",
            "acoptc_zho_hant_ocr_paddle_clean",
            Language.zho_hant,
            id="acoptc-zho-hant-paddle",
        ),
        param(
            "kob_zho_hant_ocr_fuse",
            "kob_zho_hant_ocr_fuse_clean",
            Language.zho_hant,
            id="kob-zho-hant-fuse",
        ),
        param(
            "kob_zho_hant_ocr_lens",
            "kob_zho_hant_ocr_lens_clean",
            Language.zho_hant,
            id="kob-zho-hant-lens",
        ),
        param(
            "kob_zho_hant_ocr_paddle",
            "kob_zho_hant_ocr_paddle_clean",
            Language.zho_hant,
            id="kob-zho-hant-paddle",
        ),
        param(
            "kob_yue_hans",
            "kob_yue_hans_clean",
            Language.yue_hans,
            id="kob-yue-hans-srt",
        ),
        param(
            "kob_yue_hant",
            "kob_yue_hant_clean",
            Language.yue_hant,
            id="kob-yue-hant-srt",
        ),
        param(
            "mlamd_zho_hans_fuse",
            "mlamd_zho_hans_fuse_clean",
            Language.zho_hans,
            id="mlamd-zho-hans-fuse",
        ),
        param(
            "mlamd_zho_hans_ocr_lens",
            "mlamd_zho_hans_ocr_lens_clean",
            Language.zho_hans,
            id="mlamd-zho-hans-lens",
        ),
        param(
            "mlamd_zho_hans_ocr_paddle",
            "mlamd_zho_hans_ocr_paddle_clean",
            Language.zho_hans,
            id="mlamd-zho-hans-paddle",
        ),
        param(
            "mlamd_zho_hant_fuse",
            "mlamd_zho_hant_fuse_clean",
            Language.zho_hant,
            id="mlamd-zho-hant-fuse",
        ),
        param(
            "mlamd_zho_hant_ocr_lens",
            "mlamd_zho_hant_ocr_lens_clean",
            Language.zho_hant,
            id="mlamd-zho-hant-lens",
        ),
        param(
            "mlamd_zho_hant_ocr_paddle",
            "mlamd_zho_hant_ocr_paddle_clean",
            Language.zho_hant,
            id="mlamd-zho-hant-paddle",
        ),
        param(
            "mnt_zho_hans_fuse",
            "mnt_zho_hans_fuse_clean",
            Language.zho_hans,
            id="mnt-zho-hans-fuse",
        ),
        param(
            "mnt_zho_hans_ocr_lens",
            "mnt_zho_hans_ocr_lens_clean",
            Language.zho_hans,
            id="mnt-zho-hans-lens",
        ),
        param(
            "mnt_zho_hans_ocr_paddle",
            "mnt_zho_hans_ocr_paddle_clean",
            Language.zho_hans,
            id="mnt-zho-hans-paddle",
        ),
        param(
            "mnt_zho_hant_fuse",
            "mnt_zho_hant_fuse_clean",
            Language.zho_hant,
            id="mnt-zho-hant-fuse",
        ),
        param(
            "mnt_zho_hant_ocr_lens",
            "mnt_zho_hant_ocr_lens_clean",
            Language.zho_hant,
            id="mnt-zho-hant-lens",
        ),
        param(
            "mnt_zho_hant_ocr_paddle",
            "mnt_zho_hant_ocr_paddle_clean",
            Language.zho_hant,
            id="mnt-zho-hant-paddle",
        ),
        param(
            "t_zho_hans_fuse",
            "t_zho_hans_fuse_clean",
            Language.zho_hans,
            id="t-zho-hans-fuse",
        ),
        param(
            "t_zho_hans_ocr_lens",
            "t_zho_hans_ocr_lens_clean",
            Language.zho_hans,
            id="t-zho-hans-lens",
        ),
        param(
            "t_zho_hans_ocr_paddle",
            "t_zho_hans_ocr_paddle_clean",
            Language.zho_hans,
            id="t-zho-hans-paddle",
        ),
        param(
            "t_zho_hant_fuse",
            "t_zho_hant_fuse_clean",
            Language.zho_hant,
            id="t-zho-hant-fuse",
        ),
        param(
            "t_zho_hant_ocr_lens",
            "t_zho_hant_ocr_lens_clean",
            Language.zho_hant,
            id="t-zho-hant-lens",
        ),
        param(
            "t_zho_hant_ocr_paddle",
            "t_zho_hant_ocr_paddle_clean",
            Language.zho_hant,
            id="t-zho-hant-paddle",
        ),
        param(
            "tmm_yue_hans_ocr_fuse",
            "tmm_yue_hans_ocr_fuse_clean",
            Language.yue_hans,
            id="tmm-yue-hans-fuse",
        ),
        param(
            "tmm_yue_hans_ocr_lens",
            "tmm_yue_hans_ocr_lens_clean",
            Language.yue_hans,
            id="tmm-yue-hans-lens",
        ),
        param(
            "tmm_yue_hans_ocr_paddle",
            "tmm_yue_hans_ocr_paddle_clean",
            Language.yue_hans,
            id="tmm-yue-hans-paddle",
        ),
        param(
            "tmm_yue_hant_ocr_fuse",
            "tmm_yue_hant_ocr_fuse_clean",
            Language.yue_hant,
            id="tmm-yue-hant-fuse",
        ),
        param(
            "tmm_yue_hant_ocr_lens",
            "tmm_yue_hant_ocr_lens_clean",
            Language.yue_hant,
            id="tmm-yue-hant-lens",
        ),
        param(
            "tmm_yue_hant_ocr_paddle",
            "tmm_yue_hant_ocr_paddle_clean",
            Language.yue_hant,
            id="tmm-yue-hant-paddle",
        ),
        param(
            "tmm_zho_hans_ocr_fuse",
            "tmm_zho_hans_ocr_fuse_clean",
            Language.zho_hans,
            id="tmm-zho-hans-fuse",
        ),
        param(
            "tmm_zho_hans_ocr_lens",
            "tmm_zho_hans_ocr_lens_clean",
            Language.zho_hans,
            id="tmm-zho-hans-lens",
        ),
        param(
            "tmm_zho_hans_ocr_paddle",
            "tmm_zho_hans_ocr_paddle_clean",
            Language.zho_hans,
            id="tmm-zho-hans-paddle",
        ),
        param(
            "tmm_zho_hant_ocr_fuse",
            "tmm_zho_hant_ocr_fuse_clean",
            Language.zho_hant,
            id="tmm-zho-hant-fuse",
        ),
        param(
            "tmm_zho_hant_ocr_lens",
            "tmm_zho_hant_ocr_lens_clean",
            Language.zho_hant,
            id="tmm-zho-hant-lens",
        ),
        param(
            "tmm_zho_hant_ocr_paddle",
            "tmm_zho_hant_ocr_paddle_clean",
            Language.zho_hant,
            id="tmm-zho-hant-paddle",
        ),
    ],
)
def test_clean_series(
    request: FixtureRequest,
    series_fixture: str,
    expected_fixture: str,
    language: Language,
):
    """Test cleaning against expected subtitle series.

    Arguments:
        request: pytest request for fixture lookup
        series_fixture: fixture name for input series
        expected_fixture: fixture name for expected output series
        language: language to use for cleaning
    """
    output = clean_series(
        request.getfixturevalue(series_fixture),
        language=language,
        remove_empty=False,
    )
    assert_series_equal(output, request.getfixturevalue(expected_fixture))
