#  Copyright 2017-2026 Karl T Debiec. All rights reserved. This software may be modified
#  and distributed under the terms of the BSD license. See the LICENSE file for details.
"""MLX-Audio speech-to-text backend."""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar, cast

from scinoephile.audio.transcription.exceptions import TranscriptionError
from scinoephile.common.validation import val_input_file_or_dir_path
from scinoephile.core.dependencies.transcription import import_mlx_audio_stt_load
from scinoephile.core.language import Language

__all__ = [
    "MIMO_MODEL_NAME",
    "MlxAudioBackend",
    "MlxAudioInferenceResult",
    "QWEN3_ASR_MODEL_NAME",
]

if TYPE_CHECKING:
    from scinoephile.core.dependencies.transcription import MlxAudioModel

MIMO_MODEL_NAME = "mlx-community/MiMo-V2.5-ASR-MLX"
"""Default MLX MiMo model."""

QWEN3_ASR_MODEL_NAME = "mlx-community/Qwen3-ASR-0.6B-8bit"
"""Default MLX Qwen3-ASR model."""

_MIMO_LANGUAGE_CODES = {
    Language.eng: "en",
    Language.yue_hans: "zh",
    Language.yue_hant: "zh",
    Language.zho_hans: "zh",
    Language.zho_hant: "zh",
}
"""MiMo language codes keyed by Scinoephile language."""

_QWEN3_ASR_LANGUAGE_CODES = {
    Language.eng: "English",
    Language.yue_hans: "Cantonese",
    Language.yue_hant: "Cantonese",
    Language.zho_hans: "Chinese",
    Language.zho_hant: "Chinese",
}
"""Qwen3-ASR language codes keyed by Scinoephile language."""


@dataclass(frozen=True, slots=True)
class MlxAudioInferenceResult:
    """Result of direct MLX-Audio inference."""

    text: str
    """Transcript text."""

    generation_tokens: int | None = None
    """Number of generated text tokens, when reported by the model."""


@dataclass(frozen=True, slots=True)
class _MlxAudioModelProfile:
    """Model-specific configuration for an MLX-Audio STT family."""

    family_name: str
    """Stable model-family name used in cache metadata."""
    mlx_audio_model_type: str
    """Model type passed to the MLX-Audio loader."""
    default_max_tokens: int
    """Default maximum number of text tokens generated by the model family."""
    token_limit_guard_chunk_duration_seconds: float | None
    """Guarded chunk duration, or None when the family does not require one."""
    model_name_markers: tuple[str, ...]
    """Case-insensitive substrings identifying the model family."""
    languages: Mapping[Language, str]
    """Model-specific language values keyed by Scinoephile language."""


_MLX_AUDIO_MODEL_PROFILES = (
    _MlxAudioModelProfile(
        family_name="mimo",
        mlx_audio_model_type="mimo",
        default_max_tokens=256,
        token_limit_guard_chunk_duration_seconds=55.0,
        model_name_markers=("mimo-v2.5-asr", "mimov2asr"),
        languages=_MIMO_LANGUAGE_CODES,
    ),
    _MlxAudioModelProfile(
        family_name="qwen3-asr",
        mlx_audio_model_type="qwen3_asr",
        default_max_tokens=8192,
        token_limit_guard_chunk_duration_seconds=None,
        model_name_markers=("qwen3-asr", "qwen3_asr", "qwen3asr"),
        languages=_QWEN3_ASR_LANGUAGE_CODES,
    ),
)
"""Supported MLX-Audio model profiles."""


class MlxAudioBackend:
    """Runs direct speech-to-text inference through one MLX-Audio model."""

    _models_by_reference: ClassVar[dict[str, MlxAudioModel]] = {}
    """Loaded models shared by resolved model reference."""

    def __init__(
        self, model_name: str = MIMO_MODEL_NAME, language: Language = Language.yue_hant
    ):
        """Initialize.

        Arguments:
            model_name: supported MLX-Audio model name or local model path
            language: language to transcribe
        Raises:
            ValueError: if the model family does not support the language
        """
        self.model_name = model_name
        """Supported MLX-Audio model name or local model path."""

        model_profile = _get_mlx_audio_model_profile(model_name)
        self.model_family = model_profile.family_name
        """Stable model-family name used in cache metadata."""
        self._model_type = model_profile.mlx_audio_model_type
        """Model type passed to the MLX-Audio loader."""
        self.default_max_tokens = model_profile.default_max_tokens
        """Default maximum number of generated text tokens."""

        self.token_limit_guard_chunk_duration_seconds = (
            model_profile.token_limit_guard_chunk_duration_seconds
        )
        """Guarded chunk duration, or None when the family does not require one."""

        # Convert the Scinoephile language to the selected model's value
        try:
            self.language = language
            self.mlx_audio_language = model_profile.languages[language]
        except KeyError as exc:
            raise ValueError(
                f"{language} is not supported by MLX-Audio "
                f"{self.model_family} transcription"
            ) from exc

        # Resolve local paths while preserving remote Hugging Face references
        model_reference: str | Path = model_name
        model_path = Path(model_name).expanduser()
        if model_path.exists() or model_name.startswith(("/", ".", "~")):
            model_reference = val_input_file_or_dir_path(model_name)
        self._model_reference = model_reference
        """Resolved local model path or remote Hugging Face reference."""

        self._model: MlxAudioModel | None = None
        """Loaded MLX-Audio model."""

    def transcribe(
        self, audio_path: Path, max_tokens: int | None = None
    ) -> MlxAudioInferenceResult:
        """Transcribe one audio file using MLX-Audio.

        Arguments:
            audio_path: audio file to transcribe
            max_tokens: optional maximum number of text tokens to generate
        Returns:
            normalized inference result
        Raises:
            ImportError: if MLX-Audio is unavailable
            ValueError: if the model returns malformed output
        """
        if max_tokens is None:
            result: object = self._loaded_model.generate(
                str(audio_path), language=self.mlx_audio_language
            )
        else:
            result = self._loaded_model.generate(
                str(audio_path), language=self.mlx_audio_language, max_tokens=max_tokens
            )

        # Normalize mapping- and attribute-based results
        if isinstance(result, Mapping):
            result_mapping = cast(Mapping[str, object], result)
            text = result_mapping.get("text")
            generation_tokens = result_mapping.get("generation_tokens")
        else:
            text = getattr(result, "text", None)
            generation_tokens = getattr(result, "generation_tokens", None)
        if not isinstance(text, str):
            raise ValueError("MLX-Audio inference result is missing transcript text.")
        if generation_tokens is not None and (
            not isinstance(generation_tokens, int)
            or isinstance(generation_tokens, bool)
            or generation_tokens < 0
        ):
            raise ValueError(
                "MLX-Audio inference result has an invalid generation token count."
            )

        return MlxAudioInferenceResult(text=text, generation_tokens=generation_tokens)

    @property
    def _loaded_model(self) -> MlxAudioModel:
        """Get the cached MLX-Audio model, loading it if needed.

        Returns:
            loaded MLX-Audio model
        """
        if self._model is not None:
            return self._model

        model_reference = str(self._model_reference)

        # Reuse the process-wide model cache across inference instances
        cached_model = self._models_by_reference.get(model_reference)
        if cached_model is None:
            load = import_mlx_audio_stt_load()
            cached_model = cast(
                "MlxAudioModel",
                load(self._model_reference, model_type=self._model_type),
            )
            self._models_by_reference[model_reference] = cached_model
        self._model = cached_model
        return self._model


def _get_mlx_audio_model_identity(model_name: str) -> str:
    """Get searchable identity text for a remote or local MLX-Audio model.

    Arguments:
        model_name: Hugging Face model identifier or local model path
    Returns:
        lower-case model identity text
    """
    identity_parts = [model_name]
    model_path = Path(model_name).expanduser()
    if not model_path.exists():
        return model_name.lower()

    if model_path.is_dir():
        metadata_paths = (model_path / "config.json", model_path / "mlx_manifest.json")
    elif model_path.suffix.lower() == ".json":
        metadata_paths = (model_path,)
    else:
        metadata_paths = ()

    for metadata_path in metadata_paths:
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, ValueError):
            continue
        if not isinstance(metadata, Mapping):
            continue
        for key in ("model_type", "model", "architectures", "source_model_dir"):
            value = metadata.get(key)
            if isinstance(value, str):
                identity_parts.append(value)
            elif isinstance(value, Sequence):
                identity_parts.extend(item for item in value if isinstance(item, str))

    return " ".join(identity_parts).lower()


def _get_mlx_audio_model_profile(model_name: str) -> _MlxAudioModelProfile:
    """Get the supported model profile matching an MLX-Audio model name.

    Arguments:
        model_name: Hugging Face model identifier or local model path
    Returns:
        matching model profile
    Raises:
        TranscriptionError: if the model family has not been integrated
            and tested
    """
    model_identity = _get_mlx_audio_model_identity(model_name)
    for profile in _MLX_AUDIO_MODEL_PROFILES:
        if any(marker in model_identity for marker in profile.model_name_markers):
            return profile
    supported_families = ", ".join(
        profile.family_name for profile in _MLX_AUDIO_MODEL_PROFILES
    )
    raise TranscriptionError(
        f"Unsupported MLX-Audio model {model_name!r}; supported families: "
        f"{supported_families}."
    )
