#  Copyright 2017-2026 Karl T Debiec. All rights reserved. This software may be modified
#  and distributed under the terms of the BSD license. See the LICENSE file for details.
"""Direct speech-to-text inference through MLX-Audio."""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Any, ClassVar, cast

from scinoephile.audio.transcription.exceptions import TranscriptionError
from scinoephile.common.validation import val_input_file_or_dir_path
from scinoephile.core.language import Language

__all__ = [
    "MIMO_MODEL_NAME",
    "MlxAudioInference",
    "MlxAudioInferenceResult",
    "MlxAudioModelProfile",
    "QWEN3_ASR_MODEL_NAME",
]

MIMO_MODEL_NAME = "mlx-community/MiMo-V2.5-ASR-MLX"
"""Default MLX MiMo model."""

QWEN3_ASR_MODEL_NAME = "mlx-community/Qwen3-ASR-0.6B-8bit"
"""Default MLX Qwen3-ASR model."""


@dataclass(frozen=True)
class MlxAudioInferenceResult:
    """Result of direct MLX-Audio inference."""

    text: str
    """Transcript text."""

    generation_tokens: int | None = None
    """Number of generated text tokens, when reported by the model."""


@dataclass(frozen=True, slots=True)
class MlxAudioModelProfile:
    """Model-specific configuration for an MLX-Audio STT family."""

    family_name: str
    """Stable model-family name used in cache metadata."""
    mlx_audio_model_type: str
    """Model type passed to the MLX-Audio loader."""
    default_max_tokens: int
    """Default maximum number of text tokens generated by the model family."""
    model_name_markers: tuple[str, ...]
    """Case-insensitive substrings identifying the model family."""
    language_identifiers: Mapping[Language, str]
    """Model-specific language identifiers keyed by Scinoephile language."""

    def get_language_identifier(self, language: Language) -> str:
        """Get the model-specific identifier for a language.

        Arguments:
            language: transcription language
        Returns:
            model-specific language identifier
        Raises:
            ValueError: if the model family does not support the language
        """
        try:
            return self.language_identifiers[language]
        except KeyError as exc:
            raise ValueError(
                f"{language} is not supported by MLX-Audio "
                f"{self.family_name} transcription"
            ) from exc


_MLX_AUDIO_MODEL_PROFILES = (
    MlxAudioModelProfile(
        family_name="mimo",
        mlx_audio_model_type="mimo",
        default_max_tokens=256,
        model_name_markers=("mimo-v2.5-asr", "mimov2asr"),
        language_identifiers=MappingProxyType(
            {
                Language.eng: "en",
                Language.yue_hans: "zh",
                Language.yue_hant: "zh",
                Language.zho_hans: "zh",
                Language.zho_hant: "zh",
            }
        ),
    ),
    MlxAudioModelProfile(
        family_name="qwen3-asr",
        mlx_audio_model_type="qwen3_asr",
        default_max_tokens=8192,
        model_name_markers=("qwen3-asr", "qwen3_asr", "qwen3asr"),
        language_identifiers=MappingProxyType(
            {
                Language.eng: "English",
                Language.yue_hans: "Cantonese",
                Language.yue_hant: "Cantonese",
                Language.zho_hans: "Chinese",
                Language.zho_hant: "Chinese",
            }
        ),
    ),
)
"""Supported MLX-Audio model profiles."""


class MlxAudioInference:
    """Runs direct speech-to-text inference through one MLX-Audio model."""

    _models_by_reference: ClassVar[dict[str, Any]] = {}
    """Loaded models shared by resolved model reference."""

    def __init__(self, model_name: str = MIMO_MODEL_NAME):
        """Initialize.

        Arguments:
            model_name: supported MLX-Audio model name or local model path
        """
        self.model_name = model_name
        """Supported MLX-Audio model name or local model path."""

        self.model_profile = _get_mlx_audio_model_profile(model_name)
        """Configuration for the selected MLX-Audio model family."""

        # Resolve local paths while preserving remote Hugging Face references
        model_reference: str | Path = model_name
        model_path = Path(model_name).expanduser()
        if model_path.exists() or model_name.startswith(("/", ".", "~")):
            model_reference = val_input_file_or_dir_path(model_name)
        self._model_reference = model_reference
        """Resolved local model path or remote Hugging Face reference."""

        self._model: Any | None = None
        """Loaded MLX-Audio model."""

    def transcribe(
        self,
        audio_path: Path,
        language: str,
        max_tokens: int | None = None,
    ) -> MlxAudioInferenceResult:
        """Transcribe one audio file using MLX-Audio.

        Arguments:
            audio_path: audio file to transcribe
            language: model-specific language identifier
            max_tokens: optional maximum number of text tokens to generate
        Returns:
            normalized inference result
        Raises:
            ImportError: if MLX-Audio is unavailable
            ValueError: if the model returns malformed output
        """
        generate_kwargs: dict[str, object] = {"language": language}
        if max_tokens is not None:
            generate_kwargs["max_tokens"] = max_tokens
        result = self._loaded_model.generate(str(audio_path), **generate_kwargs)

        # Normalize mapping- and attribute-based results
        if isinstance(result, Mapping):
            result_mapping = cast(Mapping[str, object], result)
            text = result_mapping.get("text")
            generation_tokens = result_mapping.get("generation_tokens")
        else:
            text = getattr(result, "text", None)
            generation_tokens = getattr(result, "generation_tokens", None)
        if not isinstance(text, str):
            raise ValueError("MLX-Audio inference result is missing transcript text.")
        if generation_tokens is not None and (
            not isinstance(generation_tokens, int)
            or isinstance(generation_tokens, bool)
            or generation_tokens < 0
        ):
            raise ValueError(
                "MLX-Audio inference result has an invalid generation token count."
            )

        return MlxAudioInferenceResult(
            text=text,
            generation_tokens=generation_tokens,
        )

    @property
    def _loaded_model(self) -> Any:
        """Get the cached MLX-Audio model, loading it if needed.

        Returns:
            loaded MLX-Audio model
        """
        if self._model is not None:
            return self._model

        model_reference = str(self._model_reference)

        # Reuse the process-wide model cache across inference instances
        cached_model = self._models_by_reference.get(model_reference)
        if cached_model is None:
            load = _import_mlx_audio_stt_load()
            cached_model = load(
                self._model_reference,
                model_type=self.model_profile.mlx_audio_model_type,
            )
            self._models_by_reference[model_reference] = cached_model
        self._model = cached_model
        return self._model


def _get_mlx_audio_model_identity(model_name: str) -> str:
    """Get searchable identity text for a remote or local MLX-Audio model.

    Arguments:
        model_name: Hugging Face model identifier or local model path
    Returns:
        lower-case model identity text
    """
    identity_parts = [model_name]
    model_path = Path(model_name).expanduser()
    if not model_path.exists():
        return " ".join(identity_parts).lower()

    if model_path.is_dir():
        metadata_paths = (
            model_path / "config.json",
            model_path / "mlx_manifest.json",
        )
    elif model_path.suffix.lower() == ".json":
        metadata_paths = (model_path,)
    else:
        metadata_paths = ()

    for metadata_path in metadata_paths:
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, ValueError):
            continue
        if not isinstance(metadata, Mapping):
            continue
        for key in ("model_type", "model", "architectures", "source_model_dir"):
            value = metadata.get(key)
            if isinstance(value, str):
                identity_parts.append(value)
            elif isinstance(value, Sequence):
                identity_parts.extend(item for item in value if isinstance(item, str))

    return " ".join(identity_parts).lower()


def _get_mlx_audio_model_profile(model_name: str) -> MlxAudioModelProfile:
    """Get the supported model profile matching an MLX-Audio model name.

    Arguments:
        model_name: Hugging Face model identifier or local model path
    Returns:
        matching model profile
    Raises:
        TranscriptionError: if the model family has not been integrated
            and tested
    """
    lowered_model_name = _get_mlx_audio_model_identity(model_name)
    for profile in _MLX_AUDIO_MODEL_PROFILES:
        if any(marker in lowered_model_name for marker in profile.model_name_markers):
            return profile
    supported_families = ", ".join(
        profile.family_name for profile in _MLX_AUDIO_MODEL_PROFILES
    )
    raise TranscriptionError(
        f"Unsupported MLX-Audio model {model_name!r}; supported families: "
        f"{supported_families}."
    )


def _import_mlx_audio_stt_load() -> Any:
    """Import the MLX-Audio STT model loader on demand.

    Returns:
        MLX-Audio STT load function
    Raises:
        ImportError: if MLX-Audio is unavailable
    """
    try:
        from mlx_audio.stt import (  # noqa: PLC0415
            load,
        )
    except ImportError as exc:
        raise ImportError(
            "MLX-Audio inference requires optional transcription dependencies. "
            "Install scinoephile with the 'transcription' extra."
        ) from exc
    return load
