#  Copyright 2017-2026 Karl T Debiec. All rights reserved. This software may be modified
#  and distributed under the terms of the BSD license. See the LICENSE file for details.
"""Audit Python files for compliance with `docs/STYLE.md`."""

from __future__ import annotations

import argparse
import ast
import re
from collections import Counter, defaultdict
from collections.abc import Sequence
from logging import INFO, basicConfig, info
from pathlib import Path
from typing import NamedTuple

__all__ = [
    "StyleNote",
    "audit_file",
    "audit_paths",
    "get_python_files",
    "main",
    "parse_args",
    "write_report",
]

COPYRIGHT_LINE_ONE_RE = re.compile(
    r"^#  Copyright \d{4}(?:-\d{4})? .+\. All rights reserved\. "
    r"This software may be modified$"
)
"""Regex matching the first line of the repository copyright header."""

COPYRIGHT_LINE_TWO_RE = re.compile(
    r"^#  and distributed under the terms of the BSD license\. "
    r"See the LICENSE file for details\.$"
)
"""Regex matching the second line of the repository copyright header."""

RST_DOUBLE_BACKTICK_RE = re.compile(r"``[^`]+``")
"""Regex matching reStructuredText-style double backticks."""

EXEMPT_RETURN_NONE_NAMES = {"__init__"}
"""Function names allowed to omit a return annotation despite no returned value."""

EXCLUDED_DIR_NAMES = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "build",
    "dist",
}
"""Directory names excluded from recursive source scans."""


class StyleNote(NamedTuple):
    """One style audit note.

    Attributes:
        category: style category
        line_number: source line number
        message: note text
    """

    category: str
    """Style category."""

    line_number: int
    """Source line number."""

    message: str
    """Note text."""


def audit_paths(target_path: Path) -> tuple[list[Path], dict[str, list[StyleNote]]]:
    """Audit all Python files under a target path.

    Arguments:
        target_path: file or directory path to audit
    Returns:
        audited files and notes keyed by POSIX path
    """
    files = get_python_files(target_path)
    notes: dict[str, list[StyleNote]] = defaultdict(list)
    for file_path in files:
        audit_file(file_path, notes)
    return files, notes


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments.

    Arguments:
        argv: optional argument sequence
    Returns:
        parsed command-line arguments
    """
    parser = argparse.ArgumentParser(
        description="Audit Python files against explicit docs/STYLE.md rules."
    )
    parser.add_argument(
        "--target",
        default=".",
        type=Path,
        help="Python file or directory to audit. Default: current directory",
    )
    parser.add_argument(
        "--output",
        default=Path("local/style_notes.md"),
        type=Path,
        help="Markdown report output path. Default: local/style_notes.md",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None):
    """Run the style audit.

    Arguments:
        argv: optional argument sequence
    """
    basicConfig(format="%(message)s", level=INFO)
    args = parse_args(argv)
    file_paths, notes = audit_paths(args.target)
    write_report(file_paths, notes, args.output, _describe_target(args.target))
    note_count = sum(len(file_notes) for file_notes in notes.values())
    info(f"wrote {args.output} with {len(file_paths)} files, {note_count} notes")


def write_report(
    file_paths: Sequence[Path],
    notes: dict[str, list[StyleNote]],
    output_path: Path,
    target_description: str = "the supplied Python files",
):
    """Write a markdown style audit report.

    Arguments:
        file_paths: audited file paths
        notes: notes keyed by POSIX path
        output_path: markdown output path
        target_description: markdown phrase describing audited files
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    category_counts = Counter(
        note.category for file_notes in notes.values() for note in file_notes
    )
    violating_files = sum(
        1 for file_path in file_paths if file_path.as_posix() in notes
    )
    clean_files = len(file_paths) - violating_files

    lines = [
        "# Style Audit Notes",
        "",
        f"Generated by a static pass over {target_description}, "
        "checked against `docs/STYLE.md`. These notes are intentionally "
        'conservative: items marked "verify" may require human judgment, '
        "especially public API choices, import locality, method ordering, and "
        "whether `print` output is user-facing.",
        "",
        "## Summary",
        "",
        f"- Files checked: {len(file_paths)}",
        f"- Files with notes: {violating_files}",
        f"- Files without notes from this pass: {clean_files}",
        f"- Total notes: {sum(category_counts.values())}",
        "",
        "## Notes by Category",
        "",
    ]
    for category, count in sorted(
        category_counts.items(), key=lambda item: (-item[1], item[0])
    ):
        lines.append(f"- {category}: {count}")
    lines.extend(
        [
            "",
            "## Audit Limitations",
            "",
            "- Ruff-managed formatting and import ordering were not run; this pass "
            "focuses on explicit `docs/STYLE.md` rules visible through source "
            "inspection.",
            "- `__all__` contents, intended public API, and `__init__.py` "
            "class-only exports require maintainer judgment.",
            "- Method/function ordering was sampled by hierarchy rules but not "
            "exhaustively proven for semantic groups; review classes and modules "
            "touched during cleanup.",
            "- Path nomenclature checks are annotation/name based and may miss "
            "unannotated path-like values or flag values that are not filesystem "
            "paths.",
            "",
            "## File-by-File Notes",
            "",
        ]
    )

    for file_path in file_paths:
        file_key = file_path.as_posix()
        lines.extend([f"### `{file_key}`", ""])
        if file_key not in notes:
            lines.append("- No notes from this static pass.")
        else:
            sorted_notes = sorted(
                notes[file_key],
                key=lambda item: (item.line_number, item.category, item.message),
            )
            lines.extend(
                f"- Line {note.line_number}: **{note.category}** - {note.message}"
                for note in sorted_notes
            )
        lines.append("")

    output_path.write_text("\n".join(lines) + "\n")


def _add_note(
    notes: dict[str, list[StyleNote]],
    file_path: Path,
    category: str,
    line_number: int,
    message: str,
):
    """Add a note to an audit result.

    Arguments:
        notes: notes keyed by POSIX path
        file_path: source file path
        category: style category
        line_number: source line number
        message: note text
    """
    notes[file_path.as_posix()].append(StyleNote(category, line_number, message))


def _arg_nodes(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[ast.arg]:
    """Get all argument nodes from a function definition.

    Arguments:
        node: function definition
    Returns:
        argument nodes
    """
    args: list[ast.arg] = []
    args.extend(node.args.posonlyargs)
    args.extend(node.args.args)
    if node.args.vararg:
        args.append(node.args.vararg)
    args.extend(node.args.kwonlyargs)
    if node.args.kwarg:
        args.append(node.args.kwarg)
    return args


def _audit_class_attributes(
    class_node: ast.ClassDef,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit documented class attribute declarations.

    Arguments:
        class_node: class definition
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    for index, item in enumerate(class_node.body):
        if not isinstance(item, ast.Assign | ast.AnnAssign):
            continue
        target = item.target if isinstance(item, ast.AnnAssign) else item.targets[0]
        name = target.id if isinstance(target, ast.Name) else None
        if not name or name.startswith("_"):
            continue
        next_item = (
            class_node.body[index + 1] if index + 1 < len(class_node.body) else None
        )
        documented = (
            isinstance(next_item, ast.Expr)
            and isinstance(next_item.value, ast.Constant)
            and isinstance(next_item.value.value, str)
        )
        if not documented:
            message = (
                f"class attribute `{class_node.name}.{name}` lacks immediate "
                "triple-quoted docstring"
            )
            _add_note(
                notes,
                file_path,
                "Documentation",
                item.lineno,
                message,
            )


def _audit_function_annotations(
    function_node: ast.FunctionDef | ast.AsyncFunctionDef,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit annotations on a function or method signature.

    Arguments:
        function_node: function or method definition
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    for arg in _arg_nodes(function_node):
        if arg.arg in {"self", "cls"}:
            continue
        if arg.annotation is None:
            message = (
                f"missing annotation for parameter `{arg.arg}` in "
                f"`{function_node.name}`"
            )
            _add_note(
                notes,
                file_path,
                "Type Annotations",
                function_node.lineno,
                message,
            )
    if function_node.returns is None:
        value_returns = [
            node
            for node in _walk_function_body(function_node)
            if isinstance(node, ast.Return)
            and node.value is not None
            and not (isinstance(node.value, ast.Constant) and node.value.value is None)
        ]
        if value_returns and function_node.name not in EXEMPT_RETURN_NONE_NAMES:
            _add_note(
                notes,
                file_path,
                "Type Annotations",
                function_node.lineno,
                f"missing return annotation for `{function_node.name}`",
            )
    elif _returns_none(function_node):
        _add_note(
            notes,
            file_path,
            "Type Annotations",
            function_node.lineno,
            f"omit explicit `-> None` for always-None `{function_node.name}`",
        )


def _audit_import(
    node: ast.ImportFrom,
    file_path: Path,
    package_name: str,
    notes: dict[str, list[StyleNote]],
):
    """Audit one `from ... import ...` statement.

    Arguments:
        node: import node
        file_path: source file path
        package_name: current package name
        notes: notes keyed by POSIX path
    """
    if node.module == "__future__":
        return
    if node.level >= 2:
        _add_note(
            notes,
            file_path,
            "Imports",
            node.lineno,
            f"parent/sibling relative import uses {node.level} leading dots",
        )
    elif node.level == 0 and node.module:
        imported_module = node.module
        same_package_import = (
            imported_module.rsplit(".", 1)[0] == package_name
            or imported_module == package_name
        )
        if (
            _is_same_top_level_package_import(file_path, imported_module)
            and same_package_import
        ):
            _add_note(
                notes,
                file_path,
                "Imports",
                node.lineno,
                "same-directory import should use relative import",
            )


def _audit_init_export(
    node: ast.ImportFrom,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
    public_exports: set[str],
):
    """Audit an import from an `__init__.py` file for class-only exports.

    Arguments:
        node: import node
        file_path: source file path
        notes: notes keyed by POSIX path
        public_exports: names listed in `__all__`
    """
    if node.module == "__future__":
        return
    for alias in node.names:
        public_name = alias.asname or alias.name
        if (
            public_name != "*"
            and public_name in public_exports
            and not public_name[0].isupper()
        ):
            message = (
                "`__init__.py` imports non-class-looking public name "
                f"`{public_name}`; verify class-only rule"
            )
            _add_note(
                notes,
                file_path,
                "Exports",
                node.lineno,
                message,
            )


def _audit_nomenclature(
    node: ast.AST,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit path-related variable and parameter names.

    Arguments:
        node: AST node
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    if isinstance(node, ast.arg):
        if (
            _is_path_annotation(node.annotation)
            and not _uses_path_nomenclature(node.arg)
            and node.arg not in {"path", "paths"}
            and not _is_cli_path_argument_name(file_path, node.arg)
            and not _is_validator_value_name(file_path, node.arg)
        ):
            _add_note(
                notes,
                file_path,
                "Nomenclature",
                node.lineno,
                f"Path parameter `{node.arg}` should use `_path`/`_paths` suffix",
            )
    elif isinstance(node, ast.Assign | ast.AnnAssign):
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        annotation = node.annotation if isinstance(node, ast.AnnAssign) else None
        for target in targets:
            if not isinstance(target, ast.Name):
                continue
            name = target.id
            if (
                _is_path_annotation(annotation)
                and not _uses_path_nomenclature(name)
                and name not in {"path", "paths"}
                and not _is_cli_path_argument_name(file_path, name)
                and not _is_validator_value_name(file_path, name)
            ):
                _add_note(
                    notes,
                    file_path,
                    "Nomenclature",
                    node.lineno,
                    f"Path variable `{name}` should use `_path`/`_paths` suffix",
                )
            if name.endswith("_directory"):
                replacement_name = f"{name.removesuffix('_directory')}_dir_path"
                _add_note(
                    notes,
                    file_path,
                    "Nomenclature",
                    node.lineno,
                    f"prefer `{replacement_name}` for path-like names",
                )
            if name.endswith("_folder"):
                replacement_name = f"{name.removesuffix('_folder')}_dir_path"
                _add_note(
                    notes,
                    file_path,
                    "Nomenclature",
                    node.lineno,
                    f"prefer `{replacement_name}` for path-like names",
                )


def _audit_required_header(
    text: str,
    lines: Sequence[str],
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit file-level copyright and future import requirements.

    Arguments:
        text: source text
        lines: source lines
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    if not text.strip():
        return
    if len(lines) < 2 or not (
        COPYRIGHT_LINE_ONE_RE.match(lines[0]) and COPYRIGHT_LINE_TWO_RE.match(lines[1])
    ):
        _add_note(
            notes,
            file_path,
            "Copyright",
            1,
            "missing or nonstandard two-line copyright header",
        )


def _audit_string_interpolation(
    node: ast.AST,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit non-f-string interpolation.

    Arguments:
        node: AST node
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    if (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "format"
        and _is_string_expr(node.func.value)
    ):
        _add_note(
            notes,
            file_path,
            "Strings",
            node.lineno,
            "uses `.format()` interpolation; prefer f-strings",
        )
    if (
        isinstance(node, ast.BinOp)
        and isinstance(node.op, ast.Mod)
        and _is_string_expr(node.left)
    ):
        _add_note(
            notes,
            file_path,
            "Strings",
            node.lineno,
            "uses `%` interpolation; prefer f-strings",
        )


def _audit_print_call(
    node: ast.AST,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit `print` calls outside CLI command output and pytest modules.

    Arguments:
        node: AST node
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    if _is_cli_module(file_path) or _is_test_module(file_path):
        return
    if (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id == "print"
    ):
        _add_note(
            notes,
            file_path,
            "Logging",
            node.lineno,
            "uses `print`; prefer `logging` outside CLI command output",
        )


def _audit_text_lines(
    lines: Sequence[str],
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit line-oriented text style rules.

    Arguments:
        lines: source lines
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    for line_number, line in enumerate(lines, 1):
        if RST_DOUBLE_BACKTICK_RE.search(line):
            _add_note(
                notes,
                file_path,
                "Documentation",
                line_number,
                "contains reStructuredText-style double backticks",
            )


def _audit_tree(
    tree: ast.Module,
    file_path: Path,
    package_name: str,
    notes: dict[str, list[StyleNote]],
):
    """Audit AST-oriented style rules.

    Arguments:
        tree: parsed module
        file_path: source file path
        package_name: current package name
        notes: notes keyed by POSIX path
    """
    public_exports = _get_all_exports(tree)
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            _audit_import(node, file_path, package_name, notes)
            if file_path.name == "__init__.py":
                _audit_init_export(node, file_path, notes, public_exports)
        elif isinstance(node, ast.ClassDef):
            _audit_class(node, file_path, notes)
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            _audit_function(node, file_path, notes)
        _audit_print_call(node, file_path, notes)
        _audit_string_interpolation(node, file_path, notes)
        _audit_nomenclature(node, file_path, notes)


def _audit_tree_header(
    tree: ast.Module,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit module docstring and export requirements.

    Arguments:
        tree: parsed module
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    if not _has_docstring(tree):
        _add_note(notes, file_path, "Documentation", 1, "missing module docstring")
    if _requires_future_annotations(tree) and not _has_future_annotations(tree):
        _add_note(
            notes,
            file_path,
            "Imports",
            1,
            "missing `from __future__ import annotations`",
        )
    all_node = _get_all_node(tree)
    if _requires_all(tree, file_path) and all_node is None:
        _add_note(notes, file_path, "Exports", 1, "missing `__all__`")
    if all_node is not None:
        _audit_all_format(all_node, file_path, notes)


def _audit_all_format(
    all_node: ast.Assign | ast.AnnAssign,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit `__all__` formatting.

    Arguments:
        all_node: `__all__` assignment
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    value = all_node.value
    if isinstance(value, ast.List | ast.Tuple | ast.Set) and len(value.elts) == 0:
        _add_note(
            notes,
            file_path,
            "Exports",
            all_node.lineno,
            "omit `__all__` when there are no public names to export",
        )
    if (
        isinstance(value, ast.List)
        and len(value.elts) == 1
        and all_node.end_lineno is not None
        and all_node.lineno != all_node.end_lineno
    ):
        _add_note(
            notes,
            file_path,
            "Exports",
            all_node.lineno,
            "single-entry `__all__` should be on one line",
        )


def _audit_class(
    class_node: ast.ClassDef,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit a class definition.

    Arguments:
        class_node: class definition
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    if not _has_docstring(class_node):
        _add_note(
            notes,
            file_path,
            "Documentation",
            class_node.lineno,
            f"missing docstring for class `{class_node.name}`",
        )
    _audit_class_attributes(class_node, file_path, notes)


def _audit_function(
    function_node: ast.FunctionDef | ast.AsyncFunctionDef,
    file_path: Path,
    notes: dict[str, list[StyleNote]],
):
    """Audit a function or method definition.

    Arguments:
        function_node: function or method definition
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    if not _is_overload(function_node) and not _has_docstring(function_node):
        _add_note(
            notes,
            file_path,
            "Documentation",
            function_node.lineno,
            f"missing docstring for {_decorated_kind(function_node)} "
            f"`{function_node.name}`",
        )
    _audit_function_annotations(function_node, file_path, notes)


def _decorated_kind(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Get a display label for a function based on decorators.

    Arguments:
        node: function or method definition
    Returns:
        function kind label
    """
    names = _decorator_names(node)
    if "property" in names:
        return "property"
    if "setter" in names:
        return "property setter"
    if "classmethod" in names:
        return "classmethod"
    if "staticmethod" in names:
        return "staticmethod"
    if "overload" in names:
        return "overload"
    return "method"


def _decorator_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[str]:
    """Get decorator names from a function.

    Arguments:
        node: function or method definition
    Returns:
        decorator names
    """
    names: list[str] = []
    for decorator in node.decorator_list:
        target = decorator.func if isinstance(decorator, ast.Call) else decorator
        if isinstance(target, ast.Name):
            names.append(target.id)
        elif isinstance(target, ast.Attribute):
            names.append(target.attr)
    return names


def _describe_target(target_path: Path) -> str:
    """Describe an audit target for the markdown report.

    Arguments:
        target_path: file or directory path being audited
    Returns:
        markdown phrase describing audited files
    """
    normalized_target_path = target_path
    if target_path == Path("."):
        return (
            "every Python file in the repository, excluding virtualenv, cache, "
            "build, and distribution directories"
        )
    if target_path.is_file():
        normalized_target_path = _get_repo_relative_path(target_path)
        return f"`{normalized_target_path.as_posix()}`"
    normalized_target_path = _get_repo_relative_path(target_path)
    return (
        f"every Python file under `{normalized_target_path.as_posix()}/`, excluding "
        "virtualenv, cache, build, and distribution directories"
    )


def _get_all_exports(tree: ast.Module) -> set[str]:
    """Get names listed in a module's `__all__`.

    Arguments:
        tree: parsed module
    Returns:
        public export names
    """
    all_node = _get_all_node(tree)
    if all_node is None:
        return set()
    value = all_node.value
    if isinstance(value, ast.List | ast.Tuple | ast.Set):
        return {
            element.value
            for element in value.elts
            if isinstance(element, ast.Constant) and isinstance(element.value, str)
        }
    return set()


def _get_all_node(tree: ast.Module) -> ast.Assign | ast.AnnAssign | None:
    """Get a module's `__all__` assignment node.

    Arguments:
        tree: parsed module
    Returns:
        `__all__` assignment, if present
    """
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "__all__"
            for target in node.targets
        ):
            return node
        if (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "__all__"
        ):
            return node
    return None


def _has_docstring(
    node: ast.AsyncFunctionDef | ast.FunctionDef | ast.ClassDef | ast.Module,
) -> bool:
    """Check whether an AST node has a docstring.

    Arguments:
        node: AST node
    Returns:
        whether a docstring is present
    """
    return ast.get_docstring(node, clean=False) is not None


def _has_future_annotations(tree: ast.Module) -> bool:
    """Check whether a module imports future annotations.

    Arguments:
        tree: parsed module
    Returns:
        whether `from __future__ import annotations` is present
    """
    return any(
        isinstance(node, ast.ImportFrom)
        and node.module == "__future__"
        and any(alias.name == "annotations" for alias in node.names)
        for node in tree.body
    )


def _has_public_exports(tree: ast.Module, file_path: Path) -> bool:
    """Check whether a module defines public exports.

    Arguments:
        tree: parsed module
        file_path: source file path
    Returns:
        whether the module defines names that should be exported
    """
    if _is_test_module(file_path):
        return False
    for node in tree.body:
        if isinstance(node, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            if not node.name.startswith("_"):
                return True
        elif isinstance(node, ast.TypeAlias) and isinstance(node.name, ast.Name):
            if not node.name.id.startswith("_"):
                return True
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if (
                    isinstance(target, ast.Name)
                    and target.id[:1].isupper()
                    and not target.id.startswith("_")
                ):
                    return True
        elif (
            file_path.name == "__init__.py"
            and isinstance(node, ast.ImportFrom)
            and node.module != "__future__"
        ):
            for alias in node.names:
                public_name = alias.asname or alias.name
                if not public_name.startswith("_"):
                    return True
    return False


def _is_path_annotation(annotation: ast.expr | None) -> bool:
    """Check whether an annotation includes a `Path` type.

    Arguments:
        annotation: annotation expression
    Returns:
        whether the annotation contains `Path` as a type node
    """
    is_path = False
    if annotation is None:
        pass
    elif isinstance(annotation, ast.Name):
        is_path = annotation.id == "Path"
    elif isinstance(annotation, ast.Attribute):
        is_path = annotation.attr == "Path"
    elif isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        is_path = _is_path_annotation(annotation.left) or _is_path_annotation(
            annotation.right
        )
    elif isinstance(annotation, ast.Constant) and isinstance(annotation.value, str):
        try:
            parsed = ast.parse(annotation.value, mode="eval")
        except SyntaxError:
            pass
        else:
            is_path = _is_path_annotation(parsed.body)
    elif isinstance(annotation, ast.Subscript):
        is_path = _is_path_annotation(annotation.slice)
    elif isinstance(annotation, ast.Tuple):
        is_path = any(_is_path_annotation(element) for element in annotation.elts)
    return is_path


def _is_overload(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    """Check whether a function is an overload stub.

    Arguments:
        node: function or method definition
    Returns:
        whether the function is decorated with `@overload`
    """
    return "overload" in _decorator_names(node)


def _is_cli_module(file_path: Path) -> bool:
    """Check whether a file belongs to the CLI package.

    Arguments:
        file_path: source file path
    Returns:
        whether the file is CLI code
    """
    parts = _get_repo_relative_path(file_path).parts
    return "cli" in parts


def _is_same_top_level_package_import(file_path: Path, imported_module: str) -> bool:
    """Check whether an import starts from the source file's top-level package.

    Arguments:
        file_path: source file path
        imported_module: imported module path
    Returns:
        whether the import starts from the same top-level package
    """
    if _is_test_module(file_path):
        return False
    module_name = _module_name_for(_get_repo_relative_path(file_path))
    top_level_name = module_name.split(".", 1)[0]
    return imported_module == top_level_name or imported_module.startswith(
        f"{top_level_name}."
    )


def _is_cli_path_argument_name(file_path: Path, name: str) -> bool:
    """Check whether a name is an allowed CLI path argument name.

    Arguments:
        file_path: source file path
        name: variable or parameter name
    Returns:
        whether the name may omit a `_path` suffix
    """
    return _is_cli_module(file_path) and (
        name.endswith("infile")
        or name.endswith("infiles")
        or name.endswith("outfile")
        or name.endswith("outfiles")
    )


def _is_validator_value_name(file_path: Path, name: str) -> bool:
    """Check whether a path-like name is an allowed validator input name.

    Arguments:
        file_path: source file path
        name: variable or parameter name
    Returns:
        whether the name may omit a `_path` suffix
    """
    relative_file_path = _get_repo_relative_path(file_path)
    return relative_file_path.name == "validation.py" and name in {
        "value",
        "value_to_validate",
    }


def _get_repo_relative_path(file_path: Path) -> Path:
    """Get a path relative to the repository root when possible.

    Arguments:
        file_path: source file path
    Returns:
        repository-relative path, or the original path if it is outside cwd
    """
    if not file_path.is_absolute():
        return file_path
    try:
        return file_path.relative_to(Path.cwd())
    except ValueError:
        return file_path


def _is_pure_package_marker(tree: ast.Module, file_path: Path) -> bool:
    """Check whether a file is a pure package marker.

    Arguments:
        tree: parsed module
        file_path: source file path
    Returns:
        whether the file is a docstring-only `__init__.py`
    """
    return (
        file_path.name == "__init__.py"
        and len(tree.body) == 1
        and isinstance(tree.body[0], ast.Expr)
        and isinstance(tree.body[0].value, ast.Constant)
        and isinstance(tree.body[0].value.value, str)
    )


def _is_test_module(file_path: Path) -> bool:
    """Check whether a file belongs to the pytest suite.

    Arguments:
        file_path: source file path
    Returns:
        whether the file is under the repository test tree
    """
    parts = _get_repo_relative_path(file_path).parts
    return bool(parts) and parts[0] == "test"


def _is_string_expr(node: ast.AST) -> bool:
    """Check whether an expression is a string literal expression.

    Arguments:
        node: AST node
    Returns:
        whether the expression is a string literal
    """
    return isinstance(node, ast.Constant) and isinstance(node.value, str)


def _module_name_for(file_path: Path) -> str:
    """Get the dotted module name for a source file.

    Arguments:
        file_path: source file path
    Returns:
        dotted module name
    """
    module_name = file_path.with_suffix("").as_posix().replace("/", ".")
    if module_name.endswith(".__init__"):
        return module_name.removesuffix(".__init__")
    return module_name


def _package_name_for(file_path: Path) -> str:
    """Get the dotted package name for a source file.

    Arguments:
        file_path: source file path
    Returns:
        dotted package name
    """
    module_name = _module_name_for(file_path)
    if file_path.name == "__init__.py":
        return module_name
    return module_name.rsplit(".", 1)[0]


def _requires_all(tree: ast.Module, file_path: Path) -> bool:
    """Check whether a module should define `__all__`.

    Arguments:
        tree: parsed module
        file_path: source file path
    Returns:
        whether `__all__` is required
    """
    return _has_public_exports(tree, file_path)


def _requires_future_annotations(tree: ast.Module) -> bool:
    """Check whether a module should import future annotations.

    Arguments:
        tree: parsed module
    Returns:
        whether `from __future__ import annotations` is required
    """
    for node in tree.body:
        if (
            isinstance(node, ast.Expr)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)
        ):
            continue
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            continue
        return True
    return False


def _returns_none(function_node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    """Check whether a function is annotated as returning `None`.

    Arguments:
        function_node: function or method definition
    Returns:
        whether the return annotation is `None`
    """
    returns = function_node.returns
    if isinstance(returns, ast.Constant) and returns.value is None:
        return True
    return isinstance(returns, ast.Name) and returns.id == "None"


def _uses_path_nomenclature(name: str) -> bool:
    """Check whether a name follows path-oriented nomenclature.

    Arguments:
        name: variable or parameter name
    Returns:
        whether the name uses explicit path nomenclature
    """
    return (
        name.endswith("_path")
        or name.endswith("_paths")
        or "_path_by_" in name
        or "_paths_by_" in name
    )


def _walk_function_body(
    function_node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> list[ast.AST]:
    """Walk a function body without descending into nested functions or classes.

    Arguments:
        function_node: function or method definition
    Returns:
        AST nodes in the function body
    """
    nodes: list[ast.AST] = []
    pending: list[ast.AST] = list(function_node.body)
    while pending:
        node = pending.pop()
        nodes.append(node)
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
            continue
        pending.extend(ast.iter_child_nodes(node))
    return nodes


def audit_file(file_path: Path, notes: dict[str, list[StyleNote]]):
    """Audit a single Python source file.

    Arguments:
        file_path: source file path
        notes: notes keyed by POSIX path
    """
    text = file_path.read_text()
    lines = text.splitlines()
    stripped = text.strip()
    package_name = _package_name_for(file_path)

    _audit_required_header(text, lines, file_path, notes)

    try:
        tree = ast.parse(text, filename=file_path.as_posix())
    except SyntaxError as err:
        _add_note(notes, file_path, "Syntax", err.lineno or 1, err.msg)
        return

    if stripped:
        _audit_tree_header(tree, file_path, notes)
    _audit_tree(tree, file_path, package_name, notes)
    _audit_text_lines(lines, file_path, notes)


def get_python_files(target_path: Path) -> list[Path]:
    """Get Python files under a target file or directory.

    Arguments:
        target_path: file or directory path
    Returns:
        sorted Python file paths
    """
    if target_path.is_file():
        return [target_path] if target_path.suffix == ".py" else []
    return sorted(
        file_path
        for file_path in target_path.rglob("*.py")
        if not _is_excluded_path(file_path, target_path)
    )


def _is_excluded_path(file_path: Path, target_path: Path) -> bool:
    """Check whether a discovered file falls under an excluded directory.

    Arguments:
        file_path: discovered file path
        target_path: recursive scan root
    Returns:
        whether the file should be omitted from the audit
    """
    relative_file_path = file_path.relative_to(target_path)
    return any(part in EXCLUDED_DIR_NAMES for part in relative_file_path.parts)


if __name__ == "__main__":
    main()
